from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('website.views',
   url(r'^$', 'home', name='home'),
   url(r'^v2.0/$', 'v2_0'),
   url(r'^terms/$', 'terms'),
   url(r'^hackaround/$', 'hackaround'),
   url(r'^bookmarklet/$', 'bookmarklet'),
   url(r'^sidespeech/$', 'sidespeech'),
   url(r'^comments-and-suggestions/$', 'comments_and_suggestions'),
   url(r'^thanks/$', 'thanks'),
   url(r'^song/(?P<song_id>\d+)/$', 'song'),
   url(r'^song/ttid/(?P<song_id>\w+)/$', 'song_ttid'),
   url(r'^room/(?P<shortcut>\w+)/$', 'room'),

   url(r'^battle/$', 'battle'),
   url(r'^ajax/battle/$', 'ajax_battle'),

   url(r'^user/(?P<user_id>\d+)/$', 'user'),
   url(r'^user/f/(?P<fbid>\d+)/$', 'user_fbid'),
   url(r'^user/uid/(?P<uid>\w+)/$', 'user_uid'),

   url(r'^chat/(?P<chatlog_id>\d+)/$', 'chat'),
   url(r'^users/$', 'users'),
   url(r'^users/appreciated/$', 'users_appreciated'),
   url(r'^users/popular/$', 'users_popular'),
   url(r'^search/$', 'search'),
   url(r'^itunes/artist/(?P<artist>.+)/song/(?P<song_name>.+)/$', 'itunes'),
   url(r'^songs/played/$', 'songs_played'),
   url(r'^songs/$', 'songs'),
   url(r'^rooms/$', 'rooms'),
   url(r'^ajax_brag/uid/(?P<uid>\d+)/$', 'ajax_uid_brag'),
   url(r'^ajax_brag/(?P<username>.+)/$', 'ajax_brag'),
   url(r'^ajax_find_account/(?P<username>.+)/$', 'ajax_find_account'),
   url(r'^ajax/home/$', 'ajax_home'),
   url(r'^ajax/room/(?P<shortcut>\w+)/$', 'ajax_room_infos'),

   url(r'^login/$', 'user_login'),
   url(r'^recovery/$', 'password_recovery'),
   url(r'^recovery/(?P<key>\w+)/$', 'password_recovery2'),
   url(r'^activate/(?P<key>\w+)/$', 'user_activate'),
   url(r'^register/$', 'user_register'),
   url(r'^logout/$', 'user_logout'),
   url(r'^profile/link/(?P<uid>\d+)/$', 'link_profile'),
   url(r'^profile/$', 'profile'),
   url(r'^profile/change-password/$', 'change_password'),
   url(r'^profile/edit/$', 'edit_profile'),
   url(r'^profile/playlists/$', 'playlists'),
   url(r'^authkey/$', 'authkey'),
   url(r'^profile/playlists/export/(?P<playlist_id>\d+)/$', 'playlists_export'),
   url(r'^profile/playlists/import/$', 'playlists_import'),
   url(r'^profile/playlists/import/save/$', 'playlists_import_save'),
   url(r'^profile/playlists/(?P<playlist_id>\d+)/$', 'playlist'),
   url(r'^profile/playlists/(?P<playlist_id>\d+)/delete-song/(?P<song_id>\d+)/$', 'playlist_remove_song'),
   url(r'^profile/playlists/edit/(?P<playlist_id>\d+)/$', 'edit_playlists'),
   url(r'^profile/playlists/delete/(?P<playlist_id>\d+)/$', 'delete_playlists'),
   url(r'^profile/playlists/add-song/(?P<song_id>\d+)/$', 'playlists_add_song'),
   url(r'^profile/playlists/create/$', 'add_playlists'),
)
